import datetime
now = datetime.datetime.now()
print(now)

html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Ops-Pipeline-Demo</title>
    <style>
        body {{ background-color: #2D2D2D; color: #ffffff; font-family: Arial, sans-serif; text-align: center; padding-top: 50px; }}
        .box {{ border: 2px solid #4CAF50; padding: 20px; display: inline-block; border-radius: 10px; }}
        h1 {{ color: #4CAF50; }}
    </style>
</head>
<body>
    <div class="box">
        <h1>Deployment Successful!</h1>
        <h2>Project: Ops-Pipeline-Demo</h2>
        <p>Generated by: <b>Python</b></p>
        <p>Served by: <b>Nginx in Docker</b></p>
        <hr>
        <p>Timestamp: {now}</p>
    </div>
</body>
</html>
"""


with open("index.html", "w") as file:
    file.write(html_content)


print(f"SUCCESS: index.html created at {now}")